import '../models/chipviewlayout_item_model.dart';import 'package:equatable/equatable.dart';import 'package:flutter/material.dart';import '/core/app_export.dart';import '../models/chipviewlayout_item_model.dart';import '../models/layout20_item_model.dart';import '../models/layout21_item_model.dart';import '../models/listshape4_item_model.dart';import '../models/gridshape6_item_model.dart';import 'package:basri_s_application27/presentation/property_details_screen/models/property_details_model.dart';part 'property_details_event.dart';part 'property_details_state.dart';class PropertyDetailsBloc extends Bloc<PropertyDetailsEvent, PropertyDetailsState> {PropertyDetailsBloc(PropertyDetailsState initialState) : super(initialState) { on<PropertyDetailsInitialEvent>(_onInitialize); on<UpdateChipViewEvent>(_updateChipView); on<ChangeDropDownEvent>(_changeDropDown); }

_onInitialize(PropertyDetailsInitialEvent event, Emitter<PropertyDetailsState> emit, ) async  { emit(state.copyWith(propertyDetailsModelObj: state.propertyDetailsModelObj?.copyWith(chipviewlayoutItemList: fillChipviewlayoutItemList(), layout20ItemList: fillLayout20ItemList(), dropdownItemList: fillDropdownItemList(), layout21ItemList: fillLayout21ItemList(), listshape4ItemList: fillListshape4ItemList(), gridshape6ItemList: fillGridshape6ItemList()))); } 
_updateChipView(UpdateChipViewEvent event, Emitter<PropertyDetailsState> emit, ) { List<ChipviewlayoutItemModel> newList = List<ChipviewlayoutItemModel>.from(state.propertyDetailsModelObj!.chipviewlayoutItemList); newList[event.index] = newList[event.index].copyWith(isSelected: event.isSelected); emit(state.copyWith(propertyDetailsModelObj: state.propertyDetailsModelObj?.copyWith(chipviewlayoutItemList: newList))); } 
_changeDropDown(ChangeDropDownEvent event, Emitter<PropertyDetailsState> emit, ) { emit(state.copyWith(selectedDropDownValue: event.value)); } 
List<ChipviewlayoutItemModel> fillChipviewlayoutItemList() { return List.generate(2, (index) => ChipviewlayoutItemModel()); } 
List<Layout20ItemModel> fillLayout20ItemList() { return List.generate(3, (index) => Layout20ItemModel()); } 
List<SelectionPopupModel> fillDropdownItemList() { return [SelectionPopupModel(id: 1, title: "Item One", isSelected: true), SelectionPopupModel(id: 2, title: "Item Two"), SelectionPopupModel(id: 3, title: "Item Three")]; } 
List<Layout21ItemModel> fillLayout21ItemList() { return List.generate(3, (index) => Layout21ItemModel()); } 
List<Listshape4ItemModel> fillListshape4ItemList() { return List.generate(2, (index) => Listshape4ItemModel()); } 
List<Gridshape6ItemModel> fillGridshape6ItemList() { return List.generate(2, (index) => Gridshape6ItemModel()); } 
 }
